openapi: '3.0.3'
info:
  version: 0.0.1
  title: User API
paths:
  /users:
    options:
      tags:
        - users
      summary: Get all options User
      operationId: getOptionsUsers
      responses:
        '200':
          description: Expected response to a valid request
    head:
      tags:
        - users
      summary: check if Users exists
      operationId: getHeadUsers
      responses:
        '204':
          description: Expected response to a valid request
        '400':
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responseError'
    get:
      tags:
        - users
      summary: Get all Users
      operationId: getAllUsers
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responseUser'
        '400':
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responseError'
    post:
      tags:
        - users
      summary: Creates a User
      operationId: createUser
      requestBody:
        description: A user to create
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/userBody'
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responseUser'
        '400':
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responseError'
    trace:
      tags:
        - users
      summary: Get all trace User
      operationId: getTraceUsers
      responses:
        '200':
          description: Expected response to a valid request
        '400':
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responseError'
  /users/{id}:
    parameters:
      - name: id
        in: path
        required: true
        description: The id of the value to return.
        schema:
          type: string
    options:
      tags:
        - users
      summary: Get all options User
      operationId: getOptionsUsersById
      responses:
        '200':
          description: Expected response to a valid request
        '400':
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responseError'
    head:
      tags:
        - users
      summary: check if userId exist
      operationId: existUserById
      responses:
        default:
          description: User exist
    get:
      tags:
        - users
      summary: Get an User
      operationId: getUserById
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responseUser'
        '400':
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responseError'
    put:
      tags:
        - users
      summary: Update an User
      operationId: putUserById
      requestBody:
        description: A user to update
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/userBody'
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responseUser'
        '400':
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responseError'
    patch:
      tags:
        - users
      summary: Update an User expecific value
      operationId: patchUserById
      requestBody:
        description: A user to update
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/userBody'
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responseUser'
        '400':
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responseError'
    delete:
      tags:
        - users
      summary: Delete user by id
      operationId: deleteUserById
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responseUser'
        '204':
          description: Expected response to a valid request
    trace:
      tags:
        - users
      summary: Get all trace User
      operationId: getTraceUsersByUserId
      responses:
        '200':
          description: Expected response to a valid request
components:
  schemas:
    # common
    data:
      required:
        - attribute
        - id
      properties:
        id:
          type: string
      discriminator:
        propertyName: type
    response:
      required:
        - uuid
        - date
        - status
        - code
        - data
      properties:
        uuid:
          type: string
          format: uuid
          nullable: false
        date:
          type: string
          format: date-time
          nullable: false
        status:
          type: string
          nullable: false
        code:
          type: string
          nullable: false
    responseError:
      required:
        - uuid
        - date
        - status
        - code
        - tittle
        - detail
        - links
        - source
      properties:
        uuid:
          type: string
          format: uuid
          nullable: false
        date:
          type: string
          format: date-time
          nullable: false
        status:
          type: string
          nullable: false
        code:
          type: string
          nullable: false
        tittle:
          type: string
          nullable: false
        detail:
          type: string
          nullable: false
        link:
          type: object
        source:
          type: object
          properties:
            pointer:
              type: string
              nullable: false
            parameter:
              type: string
              nullable: false
            header:
              type: object
        meta:
          type: object
    # body
    userBody:
      properties:
        email:
          type: string
          format: email
          nullable: false
        name:
          type: string
          nullable: false
        role:
          type: string
          nullable: false
        documentType:
          type: string
          enum:
            - DNI
            - PASSPORT
            - OTHER
    # customResponse
    responseUser:
      allOf:
        - $ref: '#/components/schemas/response'
        - type: object
          properties:
            data:
              type: array
              items:
                allOf:
                  - $ref: '#/components/schemas/userDto'
    # customRequest
    userDto:
      allOf:
        - $ref: '#/components/schemas/data'
        - type: object
          required:
            - attribute
            - type
          properties:
            attribute:
              allOf:
                - $ref: '#/components/schemas/userBody'
                - type: object
                  required:
                    - email
                    - name
                    - role
                    - documentType