server:
  port: 8000
  servlet:
    context-path: /clientApi
spring:
  application:
    name: clientApi
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/demo
    username: admin
    password: admin
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
  data:
    mongodb:
      username: admin
      password: admin
      database: admin
      port: 27017
      host: localhost
      uuid-representation: standard
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html